version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=catalog_db,1433;Database=iconic;User Id=SA;Password=Password@1;TrustServerCertificate=True
      - ConnectionStrings__Redis=distributed_cache,6379
      - StripeSettings__PublishableKey=pk_test_51QWFVfEtbctwHDRow1VMa3tv7Q4QTdggzxlgKC9W6aSKnBYRuke6vx0SFPX9LfBRBF5YLn0hP1dGqXquKKr0HUFL00qWyQd8Lp
      - StripeSettings__SecretKey=sk_test_51QWFVfEtbctwHDRop9YmISzX2O2eYoMmXaGLE1T2lZekPmghC8NQoePIKNz032LZnitcWVTxbSS1hUkm4kPwRaKr00S9pBQXF8
      - StripeSettings__WhSecret=whsec_3960800e64943d1cf44e7f6825368993386d07e9dd96c382afcc3c732db94916
    depends_on:
      - catalog_db
      - distributed_cache
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  catalog_db:
    container_name: catalog_db
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  distributed_cache:
    container_name: distributed_cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  yarpapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - api
    ports:
      - "6004:8080"
      - "6064:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
