version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: api
    build:
      context: .
      dockerfile: Services/Product/API/Dockerfile

  api1:
    image: ${DOCKER_REGISTRY-}api
    container_name: api1
    build:
      context: .
      dockerfile: Services/Product/API/Dockerfile
  
  api2:
    image: ${DOCKER_REGISTRY-}api
    container_name: api2
    build:
      context: .
      dockerfile: Services/Product/API/Dockerfile

  catalog_db:
    image: mcr.microsoft.com/mssql/server:2022-latest

  distributed_cache:
    image: redis:latest

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: YarpApiGateway/Dockerfile

volumes:
  redis-data:
  sql-data:

