version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Services/Product/API/Dockerfile

  catalog_db:
    image: mcr.microsoft.com/mssql/server:2022-latest

  distributed_cache:
    image: redis:latest

volumes:
  redis-data:
  sql-data:
