version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
      - ASPNETCORE_HTTPS_PORTS=${ASPNETCORE_HTTPS_PORTS}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - ConnectionStrings__Redis=${ConnectionStrings__Redis}
      - StripeSettings__PublishableKey=${StripeSettings__PublishableKey}
      - StripeSettings__SecretKey=${StripeSettings__SecretKey}
      - StripeSettings__WhSecret=${StripeSettings__WhSecret}
    depends_on:
      - catalog_db
      - distributed_cache
    ports:
      - "6000:${ASPNETCORE_HTTP_PORTS}"
      - "6060:${ASPNETCORE_HTTPS_PORTS}"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # api1:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  #     - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
  #     - ASPNETCORE_HTTPS_PORTS=${ASPNETCORE_HTTPS_PORTS}
  #     - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
  #     - ConnectionStrings__Redis=${ConnectionStrings__Redis}
  #     - StripeSettings__PublishableKey=${StripeSettings__PublishableKey}
  #     - StripeSettings__SecretKey=${StripeSettings__SecretKey}
  #     - StripeSettings__WhSecret=${StripeSettings__WhSecret}
  #   depends_on:
  #     - catalog_db
  #     - distributed_cache
  #   ports:
  #     - "6001:${ASPNETCORE_HTTP_PORTS}"
  #     - "6061:${ASPNETCORE_HTTPS_PORTS}"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # api2:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  #     - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
  #     - ASPNETCORE_HTTPS_PORTS=${ASPNETCORE_HTTPS_PORTS}
  #     - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
  #     - ConnectionStrings__Redis=${ConnectionStrings__Redis}
  #     - StripeSettings__PublishableKey=${StripeSettings__PublishableKey}
  #     - StripeSettings__SecretKey=${StripeSettings__SecretKey}
  #     - StripeSettings__WhSecret=${StripeSettings__WhSecret}
  #   depends_on:
  #     - catalog_db
  #     - distributed_cache
  #   ports:
  #     - "6002:${ASPNETCORE_HTTP_PORTS}"
  #     - "6062:${ASPNETCORE_HTTPS_PORTS}"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  catalog_db:
    container_name: catalog_db
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  distributed_cache:
    container_name: distributed_cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  yarpapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - api
    ports:
      - "6004:8080"
      - "6064:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
